# Generated by Django 3.1.2 on 2021-03-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20210319_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
